### ISSUE TITLE
unnecessary recompilation

### ISSUE THREAD

**Issue by twiggler** [WubbaLubba/LlvmForVS2017#2]
Hey,
Did you also experience clang recompiling all translation units on every build, even when only a few are outdated? If so, did you find a resolution?

**Comment by Trass3r** [comment]
I also noticed that.

**Comment by hia3** [comment]
There are many reasons why this might happen, but most probably it is because `msbuild` implies program database file to be `$(IntDir)vc$(PlatformToolsetVersion).pdb` (for example, `Debug\vc141.pdb`).

But when compiling with LLVM toolset, for some reason, something that looks more like $(OutDir)$(ProjectName).pdb gets generated.

Try setting pdb path as on this picture:
![image](https://user-images.githubusercontent.com/4704208/34804495-f10f13dc-f689-11e7-9987-729049da9e02.png)

If this will not help, it is easy to debug it with [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon).

**Comment by Trass3r** [comment]
Indeed
`Forcing recompile of all source files due to missing PDB "obj/v141/x64/Release/vc141.pdb"`
